### ISSUE TITLE
Add text descriptions describing the changes made to each field

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight-metadata#23]
This table shows the crosswalk, but does not explain the changes: https://opengeometadata.github.io/docs/aboutAardvark/#how-do-i-convert-my-version-10-metadata-into-aardvark

Add descriptions either to this table or make a new one.  Examples of text could be: "Updated the namespace from dc_ to dct_ and changed to accept multiple values"

**Comment by rmseifried** [comment]
Shall we add new descriptions to the [metadata spreadsheet](https://docs.google.com/spreadsheets/d/1QQjUzRe8YdPGKK4h0GYoNPTow2zZ1f0KFA0zzZyHAsk/edit#gid=438729461) before updating the OGM website?

**Comment by karenmajewicz** [comment]
Augments the crosswalk table: https://github.com/OpenGeoMetadata/opengeometadata.github.io/pull/10

**Comment by rmseifried** [comment]
In a conversation with @karenmajewicz and Keith, we thought it could be helpful to restructure the "how do I convert my metadata" table so that it contains all the Aardvark fields in order (not just the ones that can be crosswalked). The idea is this would be easier for a reader to understand at a glance what fields are new.

**Comment by rmseifried** [comment]
Closed by https://github.com/OpenGeoMetadata/opengeometadata.github.io/pull/12
